### PR TITLE
Change  __aiter__ return type to AsyncIterator

### LINKED ISSUE #5163: "Iterator[BodyPartReader]" has no attribute "__anext__"
🐞 **Describe the bug**

`BodyPartReader.__aiter__()` is declared to return `Iterator` instead of `AsyncIterator`. Introduced in https://github.com/aio-libs/aiohttp/commit/3b70bad264da8e47974264863a09d6a5fc808b39 (#4931).

💡 **To Reproduce**

Snippet to reproduce:

```Python
# rep.py
from aiohttp import web

async def handler(request: web.Request) -> None:
    reader = await request.multipart()
    async for field in reader:
        ...
```

💡 **Expected behavior**

No errors returned by mypy.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
$ mypy rep.py
rep.py:5: error: "Iterator[BodyPartReader]" has no attribute "__anext__"; maybe "__next__"?
Found 1 error in 1 file (checked 1 source file)
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.6
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /private/tmp/aiohttpbug/.venv/lib/python3.8/site-packages
Requires: multidict, chardet, yarl, async-timeout, typing-extensions, attrs
Required-by:
```
```console
$ python -m pip show multidict
# irrelevant
```
```console
$ python -m pip show yarl
# irrelevant
```

📋 **Additional context**

Version of mypy:

```console
$ python -m pip show mypy
Name: mypy
Version: 0.790
Summary: Optional static typing for Python
Home-page: http://www.mypy-lang.org/
Author: Jukka Lehtosalo
Author-email: jukka.lehtosalo@iki.fi
License: MIT License
Location: /private/tmp/aiohttpbug/.venv/lib/python3.8/site-packages
Requires: typed-ast, typing-extensions, mypy-extensions
Required-by:
```

### PR DESCRIPTION
**Pull request by blazewicz**
## What do these changes do?

Change return type of `MultipartReader.__aiter__()` and `BodyPartReader.__aiter__()` to `AsyncIterator`.

## Are there changes in behavior for the user?

No more mypy errors should for code using multipart.

## Related issue number

It fixes #5163

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

### CODE REVIEW

**Review by asvetlov — APPROVED** [review]
Thanks!

**Comment by asvetlov** [comment]
Backported manually
