### ISSUE TITLE
aiohttp.MultipartWriter.append() returns None

### ISSUE THREAD

**Issue by paulannetts** [aio-libs/aiohttp#1798]
## Long story short
Scenario is to send a multi-part message from test client containing a file with custom filename. Following the instructions from http://aiohttp.readthedocs.io/en/stable/multipart.html#sending-multipart-requests

It used to work in aiohttp 1.3.5, in aiohttp 2.0.6 it generates a None exception and the documentation doesn't mention any clear breaking change.

## Expected behaviour
It should work as v1.3.5 or the documentation should be clearly updated to a working example.

## Actual behaviour
The line `mpwriter.append` is now returning `None`, so the `part.set_content_disposition` is raising an exception.

## Steps to reproduce
```
    with aiohttp.MultipartWriter('my_multi_part') as mpwriter:
        mpwriter.append_json({'key1': 'value1', 'key2': 'value2'})
        part = mpwriter.append(open(A_FILE_PATH))
        part.set_content_disposition('attachment', filename='my_custom_file.txt')
```
## Your environment
Ubuntu 16.04, Python 3.5.2, pip install of aiohttp 2.0.6

**Comment by fafhrd91** [comment]
could you post full traceback

**Comment by paulannetts** [comment]
```
=================================== FAILURES ===================================
______________________________ test_upload_dummy _______________________________

    async def test_upload_dummy():
        A_FILE_PATH = str(os.path.dirname(os.path.realpath(__file__)) + '/data/test.txt')
        with aiohttp.MultipartWriter('my_multi_part') as mpwriter:
            mpwriter.append_json({'key1': 'value1', 'key2': 'value2'})
            part = mpwriter.append(open(A_FILE_PATH))
>           part.set_content_disposition('attachment', filename='my_custom_file.txt')
E           AttributeError: 'NoneType' object has no attribute 'set_content_disposition'

=========================== 1 failed in 0.12 seconds ===========================
```

That is the full traceback by the way, because `append()` returns None.

**Comment by m-aciek** [comment]
@fafhrd91 Did you find a workaround for your problem?

**Comment by asvetlov** [comment]
@kxepal could you take a look?

**Comment by fafhrd91** [comment]
This is not a bug. This is documentation issue related to payloads

**Comment by kxepal** [comment]
So, undocumented breaking change?

**Comment by paulannetts** [comment]
New way of doing this, using the new payload system.
```
 with aiohttp.MultipartWriter('my_multi_part') as mpwriter:
        mpwriter.append_json({'key1': 'value1', 'key2': 'value2'})
        payload = aiohttp.payload.TextIOPayload(open(A_FILE_PATH))
        payload.set_content_disposition('attachment', filename='my_custom_file.txt')
        mpwriter.append_payload(payload)
```

**Comment by asvetlov** [comment]
Yes, you are right
