### ISSUE TITLE
CookieJar error

### ISSUE THREAD

**Issue by atlantis414** [aio-libs/aiohttp#1203]
> Error handling request
> Traceback (most recent call last):
>   File "C:\Python35\lib\site-packages\aiohttp\server.py", line 261, in start
>     yield from self.handle_request(message, payload)
>   File "C:\Python35\lib\site-packages\aiohttp\web.py", line 88, in handle_request
>     resp = yield from handler(request)
>   File "C:\Python35\lib\site-packages\aiohttp_session__init__.py", line 129, in middleware
>     response = yield from handler(request)
>   File "C:/MyRepositories/zfzd_interface\Middlewares.py", line 34, in middleware_handler
>     response = await handler(request)
>   File "C:/MyRepositories/zfzd_interface/HttpServer.py", line 30, in LoginSession
>     resp = await cli.LoginSession(request, redisconn=redisconn)
>   File "C:/MyRepositories/zfzd_interface\HttpClient.py", line 66, in LoginSession
>     jar = aiohttp.CookieJar(unsafe=True)
>   File "C:\Python35\lib\site-packages\aiohttp\cookiejar.py", line 37, in **init**
>     self._next_expiration = ceil(loop.time())
> AttributeError: 'NoneType' object has no attribute 'time'

I use  environment with python 3.5.2 on Windows Server2008 R2.
In aiohttp 0.22.5 is normal,When I upgraded to 1.0.1 displays the above error

**Comment by asvetlov** [comment]
Fixed. Thanks for bug report.
