### ISSUE TITLE
StaticRoute is broken in 0.16.0

### ISSUE THREAD

**Issue by magv** [aio-libs/aiohttp#377]
Hi. In commit d6f4764bb3e070afcd42893657518150242f0d41 you removed `limit` variable from the `StaticRoute` class, but that variable is still used [over here](/KeepSafe/aiohttp/blob/3b3577aa699913662e36f29c53292d193eac2e7a/aiohttp/web_urldispatcher.py#L197). Because of this, `StaticRoute` does not work in 0.16.0 release; it throws this error:

```
...
    chunk = f.read(self.limit)
AttributeError: 'StaticRoute' object has no attribute 'limit'
```

**Comment by asvetlov** [comment]
Fixed in release 0.16.1

Thanks for report!
