### ISSUE TITLE
Error in ClientSession __del__ 

### ISSUE THREAD

**Issue by sk-** [aio-libs/aiohttp#497]
The `__del__` method of `ClientSession` available for Python >= 3.4.1 produces inconsistent tracebacks.
I'm using Aiohttp 0.17.3 on Mac Os X Yosemite, with Python 3.4.3.

With the same code I've seen the following ones:
(Note: this same code was working fine with aiohttp 0.16.5 and it also works if I just comment out https://github.com/KeepSafe/aiohttp/blob/b6bfb7afbe1b786ca396757c5a88c3822fc4057a/aiohttp/client.py#L79-L90)

``` python
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x101975b70>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/aiohttp/client.py", line 77, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/aiohttp/client.py", line 342, in close
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/aiohttp/connector.py", line 235, in close
TypeError: 'NoneType' object is not callable
```

``` python
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x102075b70>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/aiohttp/client.py", line 79, in __del__
AttributeError: 'NoneType' object has no attribute 'warn'
```

``` python
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x102175b70>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/aiohttp/client.py", line 80, in __del__
TypeError: 'NoneType' object is not callable
```

``` python
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x102175b70>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/aiohttp/client.py", line 85, in __del__
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 1036, in call_exception_handler
AttributeError: 'NoneType' object has no attribute 'error'
```

**Comment by asvetlov** [comment]
Thanks for report. It should be fixed in both `aiohttp` and `asyncio`.

**Comment by asvetlov** [comment]
This is only partial fix: the same should be done for asyncio for logger instance.

Let's leave the issue open until making asyncio fix.

**Comment by asvetlov** [comment]
@sk for sake of best practice please don't rely on garbage collector but explicitly call `session.close()` after finishing all jobs for the session.

**Comment by sk-** [comment]
@asvetlov: Thanks for pointing out that I should close the session. I was using it in a command line crawler, and the program was terminating after completing the jobs. Closing the session fixes my problem.

**Comment by asvetlov** [comment]
I did my best, aiohttp is safe now.
But asyncio itself still may raise an issue.
