### ISSUE TITLE
"Iterator[BodyPartReader]" has no attribute "__anext__"

### ISSUE THREAD

**Issue by blazewicz** [aio-libs/aiohttp#5163]
🐞 **Describe the bug**

`BodyPartReader.__aiter__()` is declared to return `Iterator` instead of `AsyncIterator`. Introduced in https://github.com/aio-libs/aiohttp/commit/3b70bad264da8e47974264863a09d6a5fc808b39 (#4931).

💡 **To Reproduce**

Snippet to reproduce:

```Python
# rep.py
from aiohttp import web

async def handler(request: web.Request) -> None:
    reader = await request.multipart()
    async for field in reader:
        ...
```

💡 **Expected behavior**

No errors returned by mypy.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
$ mypy rep.py
rep.py:5: error: "Iterator[BodyPartReader]" has no attribute "__anext__"; maybe "__next__"?
Found 1 error in 1 file (checked 1 source file)
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.8.6
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /private/tmp/aiohttpbug/.venv/lib/python3.8/site-packages
Requires: multidict, chardet, yarl, async-timeout, typing-extensions, attrs
Required-by:
```
```console
$ python -m pip show multidict
# irrelevant
```
```console
$ python -m pip show yarl
# irrelevant
```

📋 **Additional context**

Version of mypy:

```console
$ python -m pip show mypy
Name: mypy
Version: 0.790
Summary: Optional static typing for Python
Home-page: http://www.mypy-lang.org/
Author: Jukka Lehtosalo
Author-email: jukka.lehtosalo@iki.fi
License: MIT License
Location: /private/tmp/aiohttpbug/.venv/lib/python3.8/site-packages
Requires: typed-ast, typing-extensions, mypy-extensions
Required-by:
```

**Comment by asvetlov** [comment]
Ooops, I've missed this bug :(
