### ISSUE TITLE
yarl >= 1.2.1 breaks compatability with aiohttp 2.2.5 and python < 3.5.2

### ISSUE THREAD

**Issue by sp1ze** [aio-libs/aiohttp#2969]
## Long story short
Please note that i don't know if this should be treated as an issue or not. I just found it a couple of hours ago and solved it by adding yarl==1.1.1 in my requirements file. 

Please see:
aiohttp: https://pypi.org/project/aiohttp/2.2.5/ requires Python >= 3.4.2
yarl: https://pypi.org/project/yarl/ requires Pin minimal required Python to 3.5.3 (#189)

Seems aiohttp setup file uses yarl>=1.0,<2.0

## Expected behaviour

Installing aiohttp 2.2.5 should work on python >= 3.4.2 

## Actual behaviour

Import errors as of yarl 1.2.1 release (2018-04-30):
.tox/py35/lib/python3.5/site-packages/aiohttp/__init__.py:6: in <module>
    from .client import *  # noqa
.tox/py35/lib/python3.5/site-packages/aiohttp/client.py:13: in <module>
    from yarl import URL
.tox/py35/lib/python3.5/site-packages/yarl/__init__.py:11: in <module>
    from .quoting import _Quoter, _Unquoter
.tox/py35/lib/python3.5/site-packages/yarl/quoting.py:3: in <module>
    from typing import Optional, TYPE_CHECKING, cast
E   ImportError: cannot import name 'TYPE_CHECKING'

## Steps to reproduce

Use python 3.5.0.
Install aiohttp 2.2.5
Try to import aiohttp

## Your environment
Python 3.5.0
aiohttp 2.2.5

**Comment by asvetlov** [comment]
You are running unsupported aiohttp on unsupported python version.
Should we maintain this case?
