### ISSUE TITLE
Crash on import (python 3.9.0a5)

### ISSUE THREAD

**Issue by cglacet** [aio-libs/aiohttp#5217]
🐞 **Describe the bug**

```python
>>> import aiohttp 
line 11, in <module>
    import aiohttp
 File "/lib/python3.9/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
 File "lib/python3.9/site-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
 File "lib/python3.9/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
 File "/lib/python3.9/site-packages/aiohttp/helpers.py", line 48, in <module>
    from typing_extensions import Protocol
  File "/lib/python3.9/site-packages/typing_extensions.py", line 2084, in <module>
    def TypeAlias(self, parameters):
TypeError: __init__() missing 1 required positional argument: 'doc'
```

💡 **To Reproduce**

```bash
$ pyenv install 3.9.0a5
$ pyenv shell 3.9.0a5
$ pip install aiohttp
$ python -c "import aiohttp"
```

The version of `aiohttp` this installs is `3.7.2`: 

```bash
$ pip show aiotthp
Name: aiohttp
Version: 3.7.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Requires: chardet, multidict, async-timeout, attrs, yarl, typing-extensions
Required-by: kune.api-tools, kune-api-tools, aiohttp-asynctools
```

**Comment by asvetlov** [comment]
Is there any reason to use the Alpha version (Python 3.9.0a5)?
The library works fine with the released Python 3.9.0: https://github.com/aio-libs/aiohttp/runs/1384472623?check_suite_focus=true#step:7:2959

**Comment by cglacet** [comment]
No particular reason no, I was just experimenting with it and noticed this error. I just reported it so you know, just in case :)

**Comment by asvetlov** [comment]
Thanks for the report but sorry, I close it.
According to traceback, I see that third-party `typing_extensions` doesn't work with 3.9 alpha but works pretty well with 3.9 release.
Nothing to do on aiohttp side.
