### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_extra_info'

### ISSUE THREAD

**Issue by vangheem** [aio-libs/aiohttp#3335]
## Long story short

When request object is closed, `request.transport` is set to `None` which causes errors if you want to do any introspection on the request afterwards(like simply doing `request.url`)

## Expected behaviour

To be able to call `request.url` object after it is closed.

## Actual behaviour

`request.url` gives:
```
File "aiohttp/_helpers.pyx", line 32, in aiohttp._helpers.reify.__get__
  File "aiohttp/_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__
  File "/Users/nathan/wildcard/castle/lib/python3.6/site-packages/aiohttp/web_request.py", line 351, in url
    url = URL.build(scheme=self.scheme, host=self.host)
  File "aiohttp/_helpers.pyx", line 32, in aiohttp._helpers.reify.__get__
  File "aiohttp/_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__
  File "/Users/nathan/wildcard/castle/lib/python3.6/site-packages/aiohttp/web_request.py", line 295, in scheme
    if self.transport.get_extra_info('sslcontext'):
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
```

## Steps to reproduce

- create server
- finish request
- create new asyncio task with reference request object

## Your environment

- Python 3.3.6
- aiohttp 3.4.4

## extra

Similar to https://github.com/aio-libs/aiohttp/issues/816

## workaround

If you call `request.url` before the request is closed, it will be cached and you will not get this error.

**Comment by asvetlov** [comment]
Sorry. I dont follow what introspection are you talking about

**Comment by vangheem** [comment]
@asvetlov updated to hopefully be more clear.

Basically, calling `request.url` after the request is closed gives this error.

**Comment by asvetlov** [comment]
Please check aiohttp master.
The issue should be fixed by #3177

**Comment by tmendo** [comment]
@asvetlov is this not supposed to work with Pyhon 3.5.5? I tested it and got the same error as before:

```
Stopping asyncio loop on unhandled exception: AttributeError. Traceback (most recent call last): ['  File "/usr/lib64/python3.5/asyncio/sslproto.py", line 637, in _process_write_backlog\n    ssldata, offset = self._sslpipe.feed_appdata(data, offset)\n'] AttributeError: 'NoneType' object has no attribute 'feed_appdata'
```

```
pip list

Package           Version   
----------------- ----------
aio-pika          4.0.0     
aiohttp           3.4.4  
...
```

**Comment by tmendo** [comment]
nop...fix was not backported. It requires python 3.6.5

**Comment by tmendo** [comment]
Read somewhere that the fix was not backported..so it requires 3.6.5

**Comment by asvetlov** [comment]
@tmendo you are talking about the completely different bug.
Please, next time keep an issue-per-problem principle.

Anyway, regarding your question: no, the fix wan not backported because Python 3.5 is in security maintenance mode now. It means that only the Release Manager (Larry Hastings in this case) can choose what bugfixes to backport, and he should have a Very Serious Reason to do it. Basically, 3.5 is closed for bugfixes except for security vulnerabilities.

I personally was the reviewer and committer for this particular bug; the best I can advise is migrating to 3.6 (or even 3.7, 3.7.1 will be published in a week).

**Comment by asvetlov** [comment]
Close as fixed, will be published as a part of aiohttp 3.5 release
