### ISSUE TITLE
3.0 is does not work

### ISSUE THREAD

**Issue by wuyazi** [aio-libs/aiohttp#2731]
```
from aiohttp import web

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(text=text)

async def wshandler(request):
    ws = web.WebSocketResponse()
    await ws.prepare(request)

    async for msg in ws:
        if msg.type == web.MsgType.text:
            await ws.send_str("Hello, {}".format(msg.data))
        elif msg.type == web.MsgType.binary:
            await ws.send_bytes(msg.data)
        elif msg.type == web.MsgType.close:
            break

    return ws


app = web.Application()
app.router.add_get('/echo', wshandler)
app.router.add_get('/', handle)
app.router.add_get('/{name}', handle)

web.run_app(app)
```
I can run the example code at v2.3, and send request sucessfuly.
But, when i run at v3.0, the request is not have response.
When i CTRL+C to stop the server, return a error
```
Task exception was never retrieved
future: <Task finished coro=<RequestHandler.start() done, defined at /Users/wuyazi/.virtualenvs/mississippi/lib/python3.5/site-packages/aiohttp/web_protocol.py:340> exception=AttributeError("'_UnixSelectorEventLoop' object has no attribute 'create_future'",)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Users/wuyazi/.virtualenvs/mississippi/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 358, in start
    self._waiter = loop.create_future()
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'create_future'
```

**Comment by wuyazi** [comment]
Now, when i upgrade my python from v3.5.1 to v3.6.4, it is resolved.

**Comment by webknjaz** [comment]
That's because the minimum supported version is Python 3.5.3 now. It's reflected in changelog and metadata.

**Comment by asvetlov** [comment]
I surprised how is possible to install aiohttp 3 on Python 3.5.1 at all?
`pip` should prevent it.

**Comment by webknjaz** [comment]
@asvetlov `setuptools`, not `pip`. But `python_requires` check is omitted in case of outdated `setuptools` version.

**Comment by asvetlov** [comment]
Aaah.
We can raise an exception from `setup.py` but I doubt if we should care

**Comment by samuelcolvin** [comment]
Why not use `python_requires='>=3.5.3',` in `setup.py`?

**Comment by webknjaz** [comment]
@samuelcolvin it's there already, but it doesn't work if user has outdated setuptools version, which doesn't support this yet.

**Comment by samuelcolvin** [comment]
Surely by that time it's their problem.
